### PR TITLE
Fix hiding of demo warning.

### PR DESCRIPTION
**Pull request by davidlehn**
- Use simple config flags for one-time template binding.
- Add notes about improvements.

### CODE REVIEW

**Review by dlongley — APPROVED** [review]

**Comment by dlongley** [comment]
This should be a minor release (addition of new controller API surface).

**Comment by davidlehn** [comment]
I was having problems with the original `$root` implementation, which is why I started this patch, but I double checked and it's now working again.  Maybe this should change to just use ng-if and add notes on future direction vs changing how it works.

**Comment by mattcollier** [comment]
@davidlehn What is the status of this PR?

**Comment by davidlehn** [comment]
I'm not sure at the moment.  This is half baked.  Using ng-if is probably an ok idea.  But we also at some point want to rewrite how this works and avoid the global productionMode flag.

**Pull request closed without merging**
