### PR TITLE
Add configurable bootstrap container class.

### PR DESCRIPTION
**Pull request by mattcollier**
Depends on: https://github.com/digitalbazaar/bedrock-views/pull/13

### CODE REVIEW

**Comment by davidlehn** [comment]
At first glance this and the bedrock-views PR look ok.  What is it going to be used for?  Are there any timing issues with angular processing vs when bootstrap layout happens?  Any chance this could be a one-time binding?  `{{::$ctrl.config....}}`

**Comment by mattcollier** [comment]
@davidlehn Implemented a one time binding, thanks for the suggestion.

Using the `container-fluid` allows one to eliminate the large left and right margins when displayed on a large desktop display.

I don't know how to answer your question about timing issues.  Are you thinking that having a variable for the container class could be problematic?

**Comment by dlongley** [comment]
I can't decide if this is the right way to do this or not yet... sorry, no more feedback than that at this time. I'll take a second look when I can.

**Comment by dlongley** [comment]
I think the right way to do this is to create a new CSS class like "br-view-container" and use less to inherit from the `container` class by default -- and let new less files override that to inherit from `container-fluid` or do whatever they want.

**Review by dlongley — CHANGES_REQUESTED** [review]
We should change the class on that element to `br-view-container` and define it in `app.less`, by default, as a `container`. Skinning bower packages can add a new less file that replaces it with something else, for instance, `container-fluid` or some set of custom rules.

This is a style-level change and I don't think we should include the backend config in it. If I was building a frontend package to update the style/do some skinning, I would expect to do most of the in a less file, not have to add a special `bedrock/config.js` file to modify how the frontend looks in a circuitous manner via the backend config.

**Comment by dlongley** [comment]
A more configurable alternative was implemented here:

https://github.com/digitalbazaar/bedrock-angular/commit/711449a58e8be3c8a3f38c62a5524aa7227ffa74

**Pull request closed without merging**
